name: CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Deploy
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: ${{ secrets.DEPLOY_USER }}
        PORT: 22
        KEY: ${{ secrets.DEPLOY_SSHKEY }}
      with:
        source: "css/,data/,img/,js/,templates/,index.php"
        target: ${{ secrets.DEPLOY_TARGET }}
